version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
