version: '3.8'

services:
  # -------------------------
  # USERS SERVICE
  # -------------------------
  users:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: users
    env_file:
      - config/.env.dev
    environment:
      - PORT=${USERS_PORT}
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    volumes:
      - ./config:/config
    depends_on:
      - mongo

  # -------------------------
  # RESTAURANTS SERVICE
  # -------------------------
  restaurants:
    build:
      context: ./restaurantService
      dockerfile: Dockerfile
    container_name: restaurants
    env_file:
      - config/.env.dev
    environment:
      - PORT=${RESTAURANT_PORT}
    ports:
      - "${RESTAURANT_PORT}:${RESTAURANT_PORT}"
    volumes:
      - ./config:/config
    depends_on:
      - mongo

  # -------------------------
  # RESTAURANTS SERVICE SETTER
  # -------------------------
  python-service:
    build:
      context: ./restaurantService/test  # Update with the path to your Python code folder
      dockerfile: Dockerfile  # Make sure the correct Dockerfile is used
    container_name: python-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/Wolt  # Update if necessary for your app
    depends_on:
      - mongo

  # -------------------------
  # ORDERS SERVICE
  # -------------------------
  orders:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: orders
    env_file:
      - config/.env.dev
    environment:
      - PORT=${ORDERS_PORT}
    ports:
      - "${ORDERS_PORT}:${ORDERS_PORT}"
    volumes:
      - ./config:/config
    depends_on:
      - mongo

  # -------------------------
  # DELIVERY SERVICE
  # -------------------------
  delivery:
    build:
      context: ./DeliveryService
      dockerfile: Dockerfile
    container_name: delivery
    env_file:
      - config/.env.dev
    environment:
      - PORT=${DELIVERY_PORT}
    ports:
      - "${DELIVERY_PORT}:${DELIVERY_PORT}"
    volumes:
      - ./config:/config
    depends_on:
      - mongo

  # -------------------------
  # ROUTER SERVICE
  # -------------------------
  router:
    build:
      context: ./Router
      dockerfile: Dockerfile
    container_name: router
    env_file:
      - config/.env.dev
    environment:
      - PORT=${ROUTER_PORT}
    ports:
      - "${ROUTER_PORT}:${ROUTER_PORT}"
    volumes:
      - ./config:/config

  # -------------------------
  # MONGO
  # -------------------------
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
